/**
* Hide/Show items according to the number of selected entries
*/
function toggleToolButtons(smartTable) {
  actionAddToPortfolioItemBtn.style.display = 'none';
  const numChecked = smartTable.selectedCheckboxes.length;

  if (numChecked === 1) {
    actionAddBtn.style.display = 'none';
    actionUpdateBtn.style.display = 'inline-block';
    actionDeleteBtn.style.display = 'inline-block';
  } else if (numChecked > 1) {
    actionAddBtn.style.display = 'none';
    actionUpdateBtn.style.display = 'none';
    actionDeleteBtn.style.display = 'inline-block';
  } else {
    actionAddBtn.style.display = 'inline-block';
    actionUpdateBtn.style.display = 'none';
    actionDeleteBtn.style.display = 'none';
  }
}

function toggleToolButtonsForStock(smartTable) {
  const numChecked = smartTable.selectedCheckboxes.length;

  if (numChecked === 1) {
    actionAddToPortfolioItemBtn.style.display = 'inline-block';
    actionAddBtn.style.display = 'none';
    actionUpdateBtn.style.display = 'inline-block';
    actionDeleteBtn.style.display = 'inline-block';
  } else if (numChecked > 1) {
    actionAddToPortfolioItemBtn.style.display = 'inline-block';
    actionAddBtn.style.display = 'none';
    actionUpdateBtn.style.display = 'none';
    actionDeleteBtn.style.display = 'inline-block';
  } else {
    actionAddToPortfolioItemBtn.style.display = 'none';
    actionAddBtn.style.display = 'inline-block';
    actionUpdateBtn.style.display = 'none';
    actionDeleteBtn.style.display = 'none';
  }
}
function loadInForm() {
  const { view } = appConfig;
  let table;
  const formId = `update-${view}-form`;
  const formElem = document.getElementById(formId);
  const formInputs = formElem.children;

  switch (view) {
    case 'stock':
      table = stockTable;
      break;
    case 'receipts-and-issues':
      table = receiptsAndIssuesTable;
      break;
    case 'suppliers':
      table = suppliersTable;
      break;
    default:
      break;
  }

  const entryId = table.selectedCheckboxes[0].id.toString();

  const selectedEntry = table.values.find((entry) => entry[0].toString() === entryId);

  selectedEntry.forEach((field, index) => {
    formInputs[index].value = field;
  });
}

function actionAdd() {
  switchSubView('add');
}

function actionUpdate() {
  loadInForm();
  switchSubView('update');
}

function actionDelete() {
  // Show dialog asking if sure to delete
  M.Modal.getInstance(deleteModal).open();
}

function actionDeleteContinue() {
  switch (appConfig.view) {
    case 'stock':
      deleteStock();
      break;
    case 'receipts-and-issues':
      deleteReceiptsAndIssues();
      break;
    case 'suppliers':
      deleteSuppliers();
      break;
    default:
      break;
  }
}

function arrangeCashflowData(formElement) {
  const data = {};
  const formInputs = formElement.children;

  data.DATE = formInputs[0].value;

  /* For getting the value of the selected option, I use the Materialize way,
  that is to say, to get an instance of the element and use the getSelectedValues() method
  */
  const addCashflowConceptSelect = document.getElementById('add-cashflow-concept-select');
  const selectInstance = M.FormSelect.getInstance(addCashflowConceptSelect);
  [selectValue] = selectInstance.getSelectedValues();
  data.CONCEPT = selectValue;

  data.DETAILS = formInputs[2].value;
  switch (data.CONCEPT) {
    case 'income':
      data.INCOME = formInputs[3].value;
      data.OUTCOME = 0;
      break;
    case 'outcome':
    case 'expense':
      data.INCOME = 0;
      data.OUTCOME = formInputs[3].value;
      break;
    default:
      break;
  }
  data.BALANCE = 0; // Number generated by a computation
  return data;
}
