const lang = {
  en: {
    search: 'Search',
    dashboard: 'Dashboard',
    movements: 'Movements',
    sale: 'Sale',
    purchase: 'Purchase',
    cashflow: 'Cashflow',
    inventory: 'Inventory',
    stock: 'Stock',
    receiptsAndIssues: 'Receipts and issues',
    stockReceipt: 'Receipt',
    stockIssue: 'Issue',
    customers: 'Customers',
    customer: 'Customer',
    suppliers: 'Suppliers',
    supplier: 'Supplier',
    configuration: 'Configuration',
    helpAndComments: 'Help and comments',
    balance: 'Balance',
    currentMonth: 'Current month',
    income: 'Income',
    outcome: 'Outcome',
    registerSale: 'Register sale',
    registerPurchase: 'Register purchase',
    notifications: 'Notifications',
    depletedStock: 'Depleted stock',
    stockBelowMinimum: 'Stock below minimum',
    viewStock: 'View stock',
    history: 'History',
    lastThreeDaysThisMonth: 'Last three days this month',
    viewCashflow: 'View cashflow',
    date: 'Date',
    invoiceReceipt: 'Invoice/Receipt',
    invoice: 'Invoice',
    receipt: 'Receipt',
    subtotal: 'Subtotal',
    total: 'Total',
    amountPaid: 'Amount paid',
    change: 'Change',
    submit: 'Submit',
    concept: 'Concept',
    expense: 'Expense',
    details: 'Details',
    amount: 'Amount',
    cod: 'Code',
    code: 'Code',
    item: 'Item',
    description: 'Description',
    unit: 'Unit',
    unitOfMeasurement: 'Unit of measurement',
    type: 'Type',
    product: 'Product',
    service: 'Service',
    category: 'Category',
    cost: 'Cost',
    price: 'Price',
    minimumStock: 'Min.',
    inStock: 'Stock',
    qty: 'Qty',
    quantity: 'Quantity',
    parameters: 'Parameters',
    myBusiness: 'My business',
    editInfoBusinesslabel: 'Edit the information of your business. This will appear on the receipts.',
    businessName: 'Business name',
    identificationRegistryNumbersLabel: 'Identification and registry numbers.',
    telephones: 'Telephones',
    address: 'Address',
    email: 'E-mail',
    website: 'Website',
    extraInfoLabel: 'Extra info/slogan/others',
    globalParameters: 'Global parameters',
    customFormatLabel: 'Custom the format in which the app will show dates and currency.',
    dateFormat: 'Date format',
    currency: 'Currency',
    decimalSeparator: 'Decimal separator',
    comma: 'Comma',
    point: 'Point',
    cents: 'Cents',
    use: 'Use',
    doNotUse: 'Do not use',
    saveChanges: 'Save changes',
    advanced: 'Advanced',
    continueOnlyIfLabel: 'Continue only if you know what you are doing. Changes in this section can cause malfunctions.',
    backupParameters: 'Backup parameters',
    backup: 'Backup',
    database: 'Database',
    openDatabaseFolder: 'Open database folder',
  },
  es: {
    search: 'Buscar',
    dashboard: 'Panel',
    movements: 'Movimientos',
    sale: 'Venta',
    purchase: 'Compra',
    cashflow: 'Movimientos',
    inventory: 'Inventario',
    stock: 'Inventario',
    receiptsAndIssues: 'Entradas y salidas',
    stockReceipt: 'Entrada',
    stockIssue: 'Salida',
    customers: 'Clientes',
    customer: 'Clientes',
    suppliers: 'Proveedores',
    supplier: 'Proveedor',
    configuration: 'Configuración',
    helpAndComments: 'Ayuda y comentarios',
    balance: 'Saldo',
    currentMonth: 'Mes en curso',
    income: 'Ingresos',
    outcome: 'Egresos',
    registerSale: 'Registrar venta',
    registerPurchase: 'Registrar compra',
    notifications: 'Notificaciones',
    depletedStock: 'Existencias agotadas',
    stockBelowMinimum: 'Existencias por debajo del mínimo',
    viewStock: 'Ver existencias',
    history: 'Historial',
    lastThreeDaysThisMonth: 'Últimos tres días',
    viewCashflow: 'Ver movimientos',
    date: 'Fecha',
    invoiceReceipt: 'Factura/Recibo',
    invoice: 'Factura',
    receipt: 'Recibo',
    subtotal: 'Subtotal',
    total: 'Total',
    amountPaid: 'Cant. Pagada',
    change: 'Cambio',
    submit: 'Guardar',
    concept: 'Concepto',
    expense: 'Gasto',
    details: 'Detalle',
    amount: 'Monto',
    cod: 'Cód',
    code: 'Código',
    item: 'Ìtem',
    description: 'Descripción',
    unit: 'Unidad',
    unitOfMeasurement: 'Unidad de medida',
    type: 'Tipo',
    product: 'Producto',
    service: 'Servicio',
    category: 'Categoría',
    cost: 'Costo',
    price: 'Precio',
    minimumStock: 'Min.',
    inStock: 'Exist.',
    qty: 'Cant.',
    quantity: 'Cantidad',
    parameters: 'Parámetros',
    myBusiness: 'Mi negocio',
    editInfoBusinesslabel: 'Edita la información de tu negocio. Esta aparecerá en los recibos.',
    businessName: 'Nombre del negocio',
    identificationRegistryNumbersLabel: 'Números de identificación y registros',
    telephones: 'Teléfonos',
    address: 'Dirección',
    email: 'email',
    website: 'Sitio web',
    extraInfoLabel: 'Información adicional/Eslogan/Otros',
    globalParameters: 'Parámetros globales',
    customFormatLabel: 'Personaliza el formato en la que el app presentará las fechas y la moneda.',
    dateFormat: 'Formato de fecha',
    currency: 'Moneda',
    decimalSeparator: 'Separador decimal',
    comma: 'Coma',
    point: 'Punto',
    cents: 'Centavos/Céntimos',
    use: 'Usar',
    doNotUse: 'No usar',
    saveChanges: 'Guardar cambios',
    advanced: 'Avanzado',
    continueOnlyIfLabel: 'Continúa solo si sabes lo que estás haciendo. Los cambios en esta sección pueden provocar un mal funcionamiento del app.',
    backupParameters: 'Respaldar parámetros',
    backup: 'Respaldar',
    database: 'Base de datos',
    openDatabaseFolder: 'Abrir carpeta de la base de datos',
  },
  pt: {
    search: 'Buscar',
    dashboard: 'Painel',
    movements: 'Movimentos',
    sale: 'Venda',
    purchase: 'Compra',
    cashflow: 'Movimentos',
    inventory: 'Estoque',
    stock: 'Estoque',
    receiptsAndIssues: 'Entradas e saídas',
    stockReceipt: 'Entrada',
    stockIssue: 'Saída',
    customers: 'Clientes',
    customer: 'Cliente',
    suppliers: 'Fornecedores',
    supplier: 'Fornecedor',
    configuration: 'Configuração',
    helpAndComments: 'Ajuda e comentários',
    balance: 'Saldo',
    currentMonth: 'Mês atual',
    income: 'Ingresos',
    outcome: 'Egressos', // *
    registerSale: 'Cadastrar venda',
    registerPurchase: 'Cadastrar compra',
    notifications: 'Notificações',
    depletedStock: 'Estoque esgotado',
    stockBelowMinimum: 'Estoque abaixo do mínimo',
    viewStock: 'Ver estoque',
    history: 'Histórico',
    lastThreeDaysThisMonth: 'Últimos três dias',
    viewCashflow: 'Ver movimentos',
    date: 'Data',
    invoiceReceipt: 'Fatura/Recibo',
    invoice: 'Fatura',
    receipt: 'Recibo',
    subtotal: 'Subtotal',
    total: 'Total',
    amountPaid: 'Valor em dinheiro',
    change: 'Troco',
    submit: 'Salvar',
    concept: 'Conceito', // *
    expense: 'Despesa',
    details: 'Detalhes', // *
    amount: 'Valor',
    cod: 'Cód.',
    code: 'Código',
    item: 'Item',
    description: 'Descrição',
    unit: 'Unidade',
    unitOfMeasurement: 'Unidade de medida',
    type: 'Tipo',
    product: 'Produto',
    service: 'Serviço',
    category: 'Categoría',
    cost: 'Custo',
    price: 'Preço',
    minimumStock: 'Mín.',
    inStock: 'Estoque',
    qty: 'Qtde',
    quantity: 'Quantidade',
    parameters: 'Parâmetros',
    myBusiness: 'Meu negócio',
    editInfoBusinesslabel: 'Edite as informações de sua empresa. Isto aparecerá nos recibos.',
    businessName: 'Nome do negócio',
    identificationRegistryNumbersLabel: 'Números de identificação e registros',
    telephones: 'Telefones',
    address: 'Endereço',
    email: 'e-mail',
    website: 'Sítio Web',
    extraInfoLabel: 'Informações adicionais/slogan/outros',
    globalParameters: 'Parâmetros globais',
    customFormatLabel: 'Personalize os formatos nos quais o aplicativo mostrará as datas e a moeda.',
    dateFormat: 'Formato da data',
    currency: 'Formato da moeda',
    decimalSeparator: 'Separador decimal',
    comma: 'Vírgula',
    point: 'Ponto',
    cents: 'Centavos',
    use: 'Usar',
    doNotUse: 'No usar',
    saveChanges: 'Salvar mudanças',
    advanced: 'Avançado',
    continueOnlyIfLabel: 'Continue somente se você souber o que está fazendo. Alterações nesta seção podem causar mau funcionamento.',
    backupParameters: 'Backup dos parâmetros',
    backup: 'Fazer backup',
    database: 'Banco de dados',
    openDatabaseFolder: 'Abrir pasta de banco de dados',
  },
};
